### ISSUE TITLE
Potential bug in Slice.get() method.

### ISSUE THREAD

**Issue by damienklinnert** [sjturley/algo-trader-kata#1]
I've noticed that the `get()` method in slice has the symbol `TQQQ` hardcoded. Is that correct behaviour? Or are we supposed to pass the symbol name (given as an argument) through?

https://github.com/sjturley/algo-trader-kata/blob/b9a36de23d35c0aea15a87675e4cb45793674997/src/main/java/com/turleylabs/algo/trader/kata/framework/Slice.java#L66

**Comment by sjturley** [comment]
The BaseAlgorithm only ever creates TQQQ or VIX slices. For the scenario of the kata, a user should only call `get()` with TQQQ. This doesn't seem to enforce that though. If you call `get` on a VIX slice it would give you TQQQ data. I want it to return null in that scenario. 

Behavior should be:

- If TQQQ slice and `get()` is called with TQQQ parameter, return the data
- If TQQQ slice and `get()` is called with any string other than TQQQ, return null
- If VIX slice and `get()` is called with any parameter, return null

**Comment by damienklinnert** [comment]
@sjturley I've made the necessary changes for both Java and TypeScript in #3 . Now it supports the behaviour you're looking for.
